// packages/create-zenpanel/templates/svelte/src/layouts/AdminRootLayout.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { createAdminAuth } from "@/context/admin-auth-context.svelte";
  import { createAdminChatPanel } from "@/context/admin-chat-panel-context.svelte";
  import { createAdminSidebar } from "@/context/admin-sidebar-context.svelte";

  type Props = { children?: Snippet };
  let { children }: Props = $props();

  createAdminAuth();
  createAdminSidebar();
  createAdminChatPanel();
</script>

<div class="admin-shell min-h-dvh w-full">
  {@render children?.()}
</div>

// packages/create-zenpanel/templates/vue/src/layouts/AdminRootLayout.vue
<script setup lang="ts">
import { provideAdminAuth } from "@/composables/use-admin-auth";
import { provideAdminChatPanel } from "@/composables/use-admin-chat-panel";
import { provideAdminSidebar } from "@/composables/use-admin-sidebar";

provideAdminAuth();
provideAdminSidebar();
provideAdminChatPanel();
</script>

<template>
  <div class="admin-shell min-h-dvh w-full">
    <RouterView />
  </div>
</template>
