// packages/create-zenpanel/templates/vite/src/layouts/AdminAuthLayout.tsx
import { AdminGuestGuard } from "@/components/admin/auth/admin-guest-guard";
import { Outlet } from "react-router-dom";

export function AdminAuthLayout() {
  return (
    <AdminGuestGuard>
      <div className="relative isolate min-h-dvh w-full overflow-x-hidden bg-white dark:bg-gray-950">
        <Outlet />
      </div>
    </AdminGuestGuard>
  );
}

// packages/create-zenpanel/templates/vue/src/layouts/AdminAuthLayout.vue
<script setup lang="ts">
import AdminGuestGuard from "@/components/admin/auth/AdminGuestGuard.vue";
</script>

<template>
  <AdminGuestGuard>
    <div class="relative isolate min-h-dvh w-full overflow-x-hidden bg-white dark:bg-gray-950">
      <RouterView />
    </div>
  </AdminGuestGuard>
</template>
