// packages/create-zenpanel/templates/vue/src/components/admin/auth/AdminGuard.vue
<script setup lang="ts">
import { watch } from "vue";
import { useRouter } from "vue-router";
import { useAdminAuth } from "@/composables/use-admin-auth";
import AdminLoading from "@/components/admin/ui/AdminLoading.vue";

const auth = useAdminAuth();
const router = useRouter();

watch(
  () => auth.admin,
  (admin) => {
    if (!auth.loading && !admin) {
      router.replace("/admin/login");
    }
  },
  { immediate: true },
);
</script>

<template>
  <template v-if="!auth.loading && auth.admin">
    <slot />
  </template>
  <AdminLoading
    v-else
    :message="auth.loading ? 'Loading…' : 'Redirecting to sign in…'"
    full-height
  />
</template>

// src/components/admin/auth/admin-guard.tsx
"use client";

import { useAdminAuth } from "@/components/admin/auth/admin-auth-provider";
import { AdminLoading } from "@/components/admin/ui/admin-loading";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export function AdminGuard({ children }: { children: React.ReactNode }) {
  const { admin, loading } = useAdminAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !admin) {
      router.replace("/admin/login");
    }
  }, [admin, loading, router]);

  if (loading) {
    return <AdminLoading message="Loading…" fullHeight />;
  }

  if (!admin) {
    return <AdminLoading message="Redirecting to sign in…" fullHeight />;
  }

  return <>{children}</>;
}
