// packages/create-zenpanel/templates/vite/src/layouts/AdminRootLayout.tsx
import { AdminAuthProvider } from "@/components/admin/auth/admin-auth-provider";
import { AdminChatPanelProvider } from "@/context/admin-chat-panel-context";
import { AdminSidebarProvider } from "@/context/admin-sidebar-context";
import { Outlet } from "react-router-dom";

export function AdminRootLayout() {
  return (
    <div className="admin-shell min-h-dvh w-full">
      <AdminAuthProvider>
        <AdminSidebarProvider>
          <AdminChatPanelProvider>
            <Outlet />
          </AdminChatPanelProvider>
        </AdminSidebarProvider>
      </AdminAuthProvider>
    </div>
  );
}

// packages/create-zenpanel/templates/svelte/src/layouts/AdminRootLayout.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { createAdminAuth } from "@/context/admin-auth-context.svelte";
  import { createAdminChatPanel } from "@/context/admin-chat-panel-context.svelte";
  import { createAdminSidebar } from "@/context/admin-sidebar-context.svelte";

  type Props = { children?: Snippet };
  let { children }: Props = $props();

  createAdminAuth();
  createAdminSidebar();
  createAdminChatPanel();
</script>

<div class="admin-shell min-h-dvh w-full">
  {@render children?.()}
</div>
