// packages/create-zenpanel/templates/react/src/pages/admin/UsersPage.tsx
import { RecentUsersTable } from "@/components/admin/dashboard/recent-users-table";
import { AdminPageHeader } from "@/components/admin/layout/admin-page-header";
import { AdminBreadcrumbs } from "@/components/admin/ui/admin-breadcrumbs";
import { AdminLoading } from "@/components/admin/ui/admin-loading";
import { previewFetchUsers, type PortalUserRow } from "@/lib/admin-api";
import { useEffect, useState } from "react";

export default function AdminUsersPage() {
  const [users, setUsers] = useState<PortalUserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    previewFetchUsers()
      .then((res) => {
        if (!cancelled) setUsers(res.users);
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load users");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return <AdminLoading message="Loading users…" />;
  }

  if (error) {
    return (
      <div className="admin-content">
        <div className="admin-card admin-card-body text-sm text-error-500">{error}</div>
      </div>
    );
  }

  return (
    <div className="admin-content space-y-6">
      <AdminBreadcrumbs />
      <AdminPageHeader title="Users" />
      <RecentUsersTable users={users} href={null} />
    </div>
  );
}

// packages/create-zenpanel/templates/solid/src/pages/admin/UsersPage.tsx
import { RecentUsersTable } from "@/components/admin/dashboard/recent-users-table";
import { AdminPageHeader } from "@/components/admin/layout/admin-page-header";
import { AdminBreadcrumbs } from "@/components/admin/ui/admin-breadcrumbs";
import { AdminLoading } from "@/components/admin/ui/admin-loading";
import { previewFetchUsers, type PortalUserRow } from "@/lib/admin-api";
import { createResource, Show } from "solid-js";

export default function AdminUsersPage() {
  const [users] = createResource<PortalUserRow[]>(async () => {
    const res = await previewFetchUsers();
    return res.users;
  });

  return (
    <Show when={!users.loading} fallback={<AdminLoading message="Loading users…" />}>
      <Show
        when={!users.error}
        fallback={
          <div class="admin-content">
            <div class="admin-card admin-card-body text-sm text-error-500">
              {users.error instanceof Error ? users.error.message : "Failed to load users"}
            </div>
          </div>
        }
      >
        <div class="admin-content space-y-6">
          <AdminBreadcrumbs />
          <AdminPageHeader title="Users" />
          <RecentUsersTable users={users() ?? []} href={null} />
        </div>
      </Show>
    </Show>
  );
}
