// packages/create-zenpanel/templates/nextjs/src/components/admin/ui/admin-theme-toggle.tsx
"use client";

import { Moon, Sun } from "lucide-react";
import { useTheme } from "next-themes";
import { useSyncExternalStore } from "react";

type Props = {
  className?: string;
};

export function AdminThemeToggle({ className = "" }: Props) {
  const { resolvedTheme, setTheme } = useTheme();
  const mounted = useSyncExternalStore(
    () => () => {},
    () => true,
    () => false,
  );

  if (!mounted) {
    return (
      <div
        className={`h-10 w-10 shrink-0 rounded-lg border border-gray-200 dark:border-gray-800 ${className}`}
        aria-hidden
      />
    );
  }

  const isDark = resolvedTheme === "dark";

  return (
    <button
      type="button"
      onClick={() => setTheme(isDark ? "light" : "dark")}
      className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-gray-200 text-gray-600 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/30 dark:border-gray-800 dark:text-gray-400 dark:hover:bg-white/5 ${className}`}
      aria-label={isDark ? "Switch to light mode" : "Switch to dark mode"}
    >
      {isDark ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
    </button>
  );
}

// packages/create-zenpanel/templates/vue/src/components/admin/ui/AdminThemeToggle.vue
<script setup lang="ts">
import { computed } from "vue";
import { useTheme } from "@/composables/use-theme";
import { Moon, Sun } from "lucide-vue-next";

const props = defineProps<{ class?: string }>();

const theme = useTheme();
const isDark = computed(() => theme.resolvedTheme === "dark");
</script>

<template>
  <button
    type="button"
    :class="[
      'flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-gray-200 text-gray-600 transition hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/30 dark:border-gray-800 dark:text-gray-400 dark:hover:bg-white/5',
      props.class,
    ]"
    :aria-label="isDark ? 'Switch to light mode' : 'Switch to dark mode'"
    @click="theme.setTheme(isDark ? 'light' : 'dark')"
  >
    <Sun v-if="isDark" class="h-5 w-5" />
    <Moon v-else class="h-5 w-5" />
  </button>
</template>
