// packages/create-zenpanel/templates/svelte/src/components/admin/layout/AdminBackdrop.svelte
<script lang="ts">
  import { useAdminSidebar } from "@/context/admin-sidebar-context.svelte";

  const sidebar = useAdminSidebar();

  $effect(() => {
    if (!sidebar.isMobileOpen || sidebar.isDesktop) return;

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") {
        sidebar.closeMobileSidebar();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  });
</script>

{#if sidebar.isMobileOpen && !sidebar.isDesktop}
  <button
    type="button"
    class="fixed inset-0 z-40 bg-gray-900/60 backdrop-blur-[2px] lg:hidden"
    onclick={() => sidebar.closeMobileSidebar()}
    aria-label="Close navigation"
  ></button>
{/if}

// src/components/admin/layout/admin-backdrop.tsx
"use client";

import { useAdminSidebar } from "@/context/admin-sidebar-context";
import { useEffect } from "react";

export function AdminBackdrop() {
  const { isMobileOpen, isDesktop, closeMobileSidebar } = useAdminSidebar();

  useEffect(() => {
    if (!isMobileOpen || isDesktop) return;

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") {
        closeMobileSidebar();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isMobileOpen, isDesktop, closeMobileSidebar]);

  if (!isMobileOpen || isDesktop) return null;

  return (
    <button
      type="button"
      className="fixed inset-0 z-40 bg-gray-900/60 backdrop-blur-[2px] lg:hidden"
      onClick={closeMobileSidebar}
      aria-label="Close navigation"
    />
  );
}
