// packages/create-zenpanel/templates/svelte/src/pages/admin/DashboardPage.svelte
<script lang="ts">
  import ActivityFeed from "@/components/admin/dashboard/ActivityFeed.svelte";
  import DashboardSidebar from "@/components/admin/dashboard/DashboardSidebar.svelte";
  import DashboardWelcome from "@/components/admin/dashboard/DashboardWelcome.svelte";
  import RecentOrdersTable from "@/components/admin/dashboard/RecentOrdersTable.svelte";
  import RecentUsersTable from "@/components/admin/dashboard/RecentUsersTable.svelte";
  import RevenueChart from "@/components/admin/dashboard/RevenueChart.svelte";
  import StatsCards from "@/components/admin/dashboard/StatsCards.svelte";
  import AdminLoading from "@/components/admin/ui/AdminLoading.svelte";
  import { registerAdminChatPageContext } from "@/hooks/use-admin-chat-page-context.svelte";
  import {
    previewFetchActivity,
    previewFetchChartData,
    previewFetchRecentOrders,
    previewFetchStats,
    previewFetchUsers,
    type ActivityItem,
    type ChartDataPoint,
    type DashboardStats,
    type PortalUserRow,
    type RecentOrder,
  } from "@/lib/admin-api";

  const DASHBOARD_QUICK_ACTIONS = [
    {
      id: "growth",
      label: "Analyze growth",
      prompt: "Analyze our user growth metrics and summarize key trends",
    },
    {
      id: "revenue",
      label: "Revenue summary",
      prompt: "Summarize revenue and order performance for this week",
    },
    {
      id: "help",
      label: "What can you do?",
      prompt: "What can you help me with on the dashboard?",
    },
  ];

  type DashboardData = {
    stats: DashboardStats;
    users: PortalUserRow[];
    chart: ChartDataPoint[];
    activity: ActivityItem[];
    orders: RecentOrder[];
  };

  async function fetchDashboardData(): Promise<DashboardData> {
    const [statsRes, usersRes, chartRes, activityRes, ordersRes] = await Promise.all([
      previewFetchStats(),
      previewFetchUsers(),
      previewFetchChartData(),
      previewFetchActivity(),
      previewFetchRecentOrders(),
    ]);

    return {
      stats: statsRes.stats,
      users: usersRes.users,
      chart: chartRes.chart,
      activity: activityRes.activity,
      orders: ordersRes.orders,
    };
  }

  let data = $state<DashboardData | null>(null);
  let loading = $state(true);
  let error = $state<unknown>(null);

  $effect(() => {
    loading = true;
    error = null;
    fetchDashboardData()
      .then((result) => {
        data = result;
      })
      .catch((err) => {
        error = err;
      })
      .finally(() => {
        loading = false;
      });
  });

  registerAdminChatPageContext(() => ({
    pageId: "dashboard",
    title: "Dashboard",
    route: "/admin",
    description:
      "Analyze metrics, summarize revenue and orders, or get suggestions for your admin workflow.",
    getSnapshot: () => {
      const stats = data?.stats;
      return stats
        ? {
            totalUsers: stats.totalUsers,
            totalRevenue: stats.totalRevenue,
            newOrdersLast7Days: stats.newOrdersLast7Days,
            unreadMessages: stats.unreadMessages,
            totalProjects: stats.totalProjects,
            newsletterSubscribers: stats.newsletterSubscribers,
            newUsersLast7Days: stats.newUsersLast7Days,
          }
        : {};
    },
    quickActions: DASHBOARD_QUICK_ACTIONS,
  }));
</script>

{#if loading}
  <AdminLoading message="Loading dashboard…" />
{:else if error}
  <div class="admin-card admin-card-body text-sm text-error-500">
    {error instanceof Error ? error.message : "Failed to load dashboard"}
  </div>
{:else if data}
  <div class="admin-content space-y-5">
    <DashboardWelcome />
    <StatsCards stats={data.stats} />

    <div class="grid items-start gap-5 xl:grid-cols-3">
      <div class="space-y-5 xl:col-span-2">
        {#if data.chart.length > 0}
          <RevenueChart data={data.chart} />
        {/if}
        <ActivityFeed items={data.activity} />
      </div>

      <DashboardSidebar usersByProvider={data.stats.usersByProvider} totalUsers={data.stats.totalUsers} />
    </div>

    <div class="grid gap-5 lg:grid-cols-2">
      <RecentOrdersTable orders={data.orders} />
      <RecentUsersTable users={data.users} />
    </div>
  </div>
{/if}

// packages/create-zenpanel/templates/vue/src/pages/admin/DashboardPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import ActivityFeed from "@/components/admin/dashboard/ActivityFeed.vue";
import DashboardSidebar from "@/components/admin/dashboard/DashboardSidebar.vue";
import DashboardWelcome from "@/components/admin/dashboard/DashboardWelcome.vue";
import RecentOrdersTable from "@/components/admin/dashboard/RecentOrdersTable.vue";
import RecentUsersTable from "@/components/admin/dashboard/RecentUsersTable.vue";
import RevenueChart from "@/components/admin/dashboard/RevenueChart.vue";
import StatsCards from "@/components/admin/dashboard/StatsCards.vue";
import AdminLoading from "@/components/admin/ui/AdminLoading.vue";
import { useAdminChatPageContext } from "@/composables/use-admin-chat-page-context";
import {
  previewFetchActivity,
  previewFetchChartData,
  previewFetchRecentOrders,
  previewFetchStats,
  previewFetchUsers,
  type ActivityItem,
  type ChartDataPoint,
  type DashboardStats,
  type PortalUserRow,
  type RecentOrder,
} from "@/lib/admin-api";

const DASHBOARD_QUICK_ACTIONS = [
  {
    id: "growth",
    label: "Analyze growth",
    prompt: "Analyze our user growth metrics and summarize key trends",
  },
  {
    id: "revenue",
    label: "Revenue summary",
    prompt: "Summarize revenue and order performance for this week",
  },
  {
    id: "help",
    label: "What can you do?",
    prompt: "What can you help me with on the dashboard?",
  },
];

type DashboardData = {
  stats: DashboardStats;
  users: PortalUserRow[];
  chart: ChartDataPoint[];
  activity: ActivityItem[];
  orders: RecentOrder[];
};

async function fetchDashboardData(): Promise<DashboardData> {
  const [statsRes, usersRes, chartRes, activityRes, ordersRes] = await Promise.all([
    previewFetchStats(),
    previewFetchUsers(),
    previewFetchChartData(),
    previewFetchActivity(),
    previewFetchRecentOrders(),
  ]);

  return {
    stats: statsRes.stats,
    users: usersRes.users,
    chart: chartRes.chart,
    activity: activityRes.activity,
    orders: ordersRes.orders,
  };
}

const data = ref<DashboardData | null>(null);
const loading = ref(true);
const error = ref<unknown>(null);

onMounted(() => {
  loading.value = true;
  error.value = null;
  fetchDashboardData()
    .then((result) => {
      data.value = result;
    })
    .catch((err) => {
      error.value = err;
    })
    .finally(() => {
      loading.value = false;
    });
});

const chatContext = computed(() => ({
  pageId: "dashboard",
  title: "Dashboard",
  route: "/admin",
  description:
    "Analyze metrics, summarize revenue and orders, or get suggestions for your admin workflow.",
  getSnapshot: () => {
    const stats = data.value?.stats;
    return stats
      ? {
          totalUsers: stats.totalUsers,
          totalRevenue: stats.totalRevenue,
          newOrdersLast7Days: stats.newOrdersLast7Days,
          unreadMessages: stats.unreadMessages,
          totalProjects: stats.totalProjects,
          newsletterSubscribers: stats.newsletterSubscribers,
          newUsersLast7Days: stats.newUsersLast7Days,
        }
      : {};
  },
  quickActions: DASHBOARD_QUICK_ACTIONS,
}));

useAdminChatPageContext(chatContext);
</script>

<template>
  <AdminLoading v-if="loading" message="Loading dashboard…" />
  <div v-else-if="error" class="admin-card admin-card-body text-sm text-error-500">
    {{ error instanceof Error ? error.message : "Failed to load dashboard" }}
  </div>
  <div v-else-if="data" class="admin-content space-y-5">
    <DashboardWelcome />
    <StatsCards :stats="data.stats" />

    <div class="grid items-start gap-5 xl:grid-cols-3">
      <div class="space-y-5 xl:col-span-2">
        <RevenueChart v-if="data.chart.length > 0" :data="data.chart" />
        <ActivityFeed :items="data.activity" />
      </div>

      <DashboardSidebar
        :users-by-provider="data.stats.usersByProvider"
        :total-users="data.stats.totalUsers"
      />
    </div>

    <div class="grid gap-5 lg:grid-cols-2">
      <RecentOrdersTable :orders="data.orders" />
      <RecentUsersTable :users="data.users" />
    </div>
  </div>
</template>
