// src/components/admin/layout/admin-backdrop.tsx
"use client";

import { useAdminSidebar } from "@/context/admin-sidebar-context";
import { useEffect } from "react";

export function AdminBackdrop() {
  const { isMobileOpen, isDesktop, closeMobileSidebar } = useAdminSidebar();

  useEffect(() => {
    if (!isMobileOpen || isDesktop) return;

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") {
        closeMobileSidebar();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isMobileOpen, isDesktop, closeMobileSidebar]);

  if (!isMobileOpen || isDesktop) return null;

  return (
    <button
      type="button"
      className="fixed inset-0 z-40 bg-gray-900/60 backdrop-blur-[2px] lg:hidden"
      onClick={closeMobileSidebar}
      aria-label="Close navigation"
    />
  );
}

// packages/create-zenpanel/templates/vue/src/components/admin/layout/AdminBackdrop.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from "vue";
import { useAdminSidebar } from "@/composables/use-admin-sidebar";

const sidebar = useAdminSidebar();

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    sidebar.closeMobileSidebar();
  }
}

onMounted(() => {
  document.addEventListener("keydown", handleKeyDown);
});

onUnmounted(() => {
  document.removeEventListener("keydown", handleKeyDown);
});
</script>

<template>
  <button
    v-if="sidebar.isMobileOpen && !sidebar.isDesktop"
    type="button"
    class="fixed inset-0 z-40 bg-gray-900/60 backdrop-blur-[2px] lg:hidden"
    aria-label="Close navigation"
    @click="sidebar.closeMobileSidebar()"
  />
</template>
