// packages/create-zenpanel/templates/vue/src/components/admin/auth/AdminGuestGuard.vue
<script setup lang="ts">
import { watch } from "vue";
import { useRouter } from "vue-router";
import { useAdminAuth } from "@/composables/use-admin-auth";
import AdminLoading from "@/components/admin/ui/AdminLoading.vue";

const auth = useAdminAuth();
const router = useRouter();

watch(
  () => auth.admin,
  (admin) => {
    if (!auth.loading && admin) {
      router.replace("/admin");
    }
  },
  { immediate: true },
);
</script>

<template>
  <template v-if="!auth.loading && !auth.admin">
    <slot />
  </template>
  <AdminLoading
    v-else
    :message="auth.loading ? 'Loading…' : 'Redirecting to dashboard…'"
    full-height
  />
</template>

// packages/create-zenpanel/templates/svelte/src/components/admin/auth/AdminGuestGuard.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useAdminAuth } from "@/context/admin-auth-context.svelte";
  import { navigate } from "@/lib/router.svelte";
  import AdminLoading from "@/components/admin/ui/AdminLoading.svelte";

  type Props = { children?: Snippet };
  let { children }: Props = $props();

  const auth = useAdminAuth();

  $effect(() => {
    if (!auth.loading && auth.admin) {
      navigate("/admin", { replace: true });
    }
  });
</script>

{#if !auth.loading && !auth.admin}
  {@render children?.()}
{:else}
  <AdminLoading message={auth.loading ? "Loading…" : "Redirecting to dashboard…"} fullHeight />
{/if}
