// packages/create-zenpanel/templates/solid/src/components/admin/layout/admin-page-header.tsx
import { Show, type JSX } from "solid-js";

type Props = {
  title: string;
  actions?: JSX.Element;
};

export function AdminPageHeader(props: Props) {
  return (
    <div class="mb-6 flex flex-col gap-4 sm:mb-8 sm:flex-row sm:items-start sm:justify-between">
      <div class="min-w-0 flex-1">
        <h1 class="truncate text-xl font-semibold tracking-tight text-gray-900 dark:text-white sm:text-2xl">
          {props.title}
        </h1>
      </div>
      <Show when={props.actions}>
        <div class="flex shrink-0 flex-wrap items-center gap-2">{props.actions}</div>
      </Show>
    </div>
  );
}

// packages/create-zenpanel/templates/nextjs/src/components/admin/layout/admin-page-header.tsx
import type { ReactNode } from "react";

type Props = {
  title: string;
  actions?: ReactNode;
};

export function AdminPageHeader({ title, actions }: Props) {
  return (
    <div className="mb-6 flex flex-col gap-4 sm:mb-8 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0 flex-1">
        <h1 className="truncate text-xl font-semibold tracking-tight text-gray-900 dark:text-white sm:text-2xl">
          {title}
        </h1>
      </div>
      {actions && (
        <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>
      )}
    </div>
  );
}
