// packages/create-zenpanel/templates/svelte/src/components/admin/ui/AdminEmptyState.svelte
<script lang="ts">
  import type { LucideIcon } from "@/lib/icon-types";
  import type { Snippet } from "svelte";

  type Props = {
    icon: LucideIcon;
    title: string;
    description: string;
    action?: Snippet;
  };

  let { icon: Icon, title, description, action }: Props = $props();
</script>

<div class="flex flex-col items-center px-6 py-16 text-center">
  <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-gray-100 dark:bg-white/5">
    <Icon class="h-7 w-7 text-gray-400 dark:text-gray-500" aria-hidden={true} />
  </div>
  <h3 class="mt-4 text-base font-semibold text-gray-900 dark:text-white">{title}</h3>
  <p class="mt-2 max-w-sm text-sm leading-relaxed text-gray-500 dark:text-gray-400">
    {description}
  </p>
  {#if action}
    <div class="mt-6">
      {@render action()}
    </div>
  {/if}
</div>

// packages/create-zenpanel/templates/vite/src/components/admin/ui/admin-empty-state.tsx
import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";

type Props = {
  icon: LucideIcon;
  title: string;
  description: string;
  action?: ReactNode;
};

export function AdminEmptyState({ icon: Icon, title, description, action }: Props) {
  return (
    <div className="flex flex-col items-center px-6 py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gray-100 dark:bg-white/5">
        <Icon className="h-7 w-7 text-gray-400 dark:text-gray-500" aria-hidden />
      </div>
      <h3 className="mt-4 text-base font-semibold text-gray-900 dark:text-white">{title}</h3>
      <p className="mt-2 max-w-sm text-sm leading-relaxed text-gray-500 dark:text-gray-400">
        {description}
      </p>
      {action && <div className="mt-6">{action}</div>}
    </div>
  );
}
