// packages/create-zenpanel/templates/solid/src/hooks/use-is-desktop.ts
import { createSignal, onCleanup, onMount } from "solid-js";

export const DESKTOP_BREAKPOINT = 1024;

export function useIsDesktop() {
  const [isDesktop, setIsDesktop] = createSignal(false);

  onMount(() => {
    const mq = window.matchMedia(`(min-width: ${DESKTOP_BREAKPOINT}px)`);
    setIsDesktop(mq.matches);

    const onChange = () => setIsDesktop(mq.matches);
    mq.addEventListener("change", onChange);
    onCleanup(() => mq.removeEventListener("change", onChange));
  });

  return isDesktop;
}

// packages/create-zenpanel/templates/react/src/hooks/use-is-desktop.ts
import { useSyncExternalStore } from "react";

export const DESKTOP_BREAKPOINT = 1024;

function getMediaQuery() {
  return window.matchMedia(`(min-width: ${DESKTOP_BREAKPOINT}px)`);
}

function subscribeDesktop(onStoreChange: () => void) {
  const mq = getMediaQuery();
  mq.addEventListener("change", onStoreChange);
  return () => mq.removeEventListener("change", onStoreChange);
}

function getDesktopSnapshot() {
  return getMediaQuery().matches;
}

function getServerDesktopSnapshot() {
  return false;
}

export function useIsDesktop() {
  return useSyncExternalStore(
    subscribeDesktop,
    getDesktopSnapshot,
    getServerDesktopSnapshot,
  );
}
