// packages/create-zenpanel/templates/svelte/src/components/admin/chat/AdminChatRouteBridge.svelte
<script lang="ts">
  import { useAdminChatPanel } from "@/context/admin-chat-panel-context.svelte";
  import { matchAdminNavItem, normalizePathname } from "@/lib/admin-nav";
  import { usePathname } from "@/lib/router.svelte";

  const pathname = usePathname();
  const chat = useAdminChatPanel();

  $effect(() => {
    const path = normalizePathname(pathname.current);

    if (path === "/admin") {
      return;
    }

    const nav = matchAdminNavItem(path);

    chat.setPageContext({
      pageId: path,
      title: nav?.name ?? "Admin",
      description:
        nav?.description ??
        `Ask me anything about ${nav?.name ?? "this page"} — analyze data, get suggestions, or plan your next steps.`,
      route: path,
      getSnapshot: () => ({ route: path }),
    });

    return () => chat.setPageContext(null);
  });
</script>

// packages/create-zenpanel/templates/vue/src/components/admin/chat/AdminChatRouteBridge.vue
<script setup lang="ts">
import { onUnmounted, watch } from "vue";
import { useRoute } from "vue-router";
import { useAdminChatPanel } from "@/composables/use-admin-chat-panel";
import { matchAdminNavItem, normalizePathname } from "@/lib/admin-nav";

const route = useRoute();
const chat = useAdminChatPanel();

const stop = watch(
  () => route.path,
  (pathValue) => {
    const path = normalizePathname(pathValue);

    if (path === "/admin") {
      return;
    }

    const nav = matchAdminNavItem(path);

    chat.setPageContext({
      pageId: path,
      title: nav?.name ?? "Admin",
      description:
        nav?.description ??
        `Ask me anything about ${nav?.name ?? "this page"} — analyze data, get suggestions, or plan your next steps.`,
      route: path,
      getSnapshot: () => ({ route: path }),
    });
  },
  { immediate: true },
);

onUnmounted(() => {
  stop();
  chat.setPageContext(null);
});
</script>

<template />
