// packages/create-zenpanel/templates/angular/src/app/admin/layout/admin-shell.component.ts
import {
  Component,
  computed,
  DestroyRef,
  inject,
  OnInit,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink, RouterOutlet } from '@angular/router';
import { filter } from 'rxjs/operators';
import { toSignal } from '@angular/core/rxjs-interop';
import { map, startWith } from 'rxjs';
import {
  adminConfig,
  adminNavItems,
  SIDEBAR_WIDTH_COLLAPSED,
  SIDEBAR_WIDTH_EXPANDED,
} from '@/app/core/admin.config';
import { AuthService } from '@/app/core/auth.service';
import { SidebarService } from '@/app/core/sidebar.service';
import { ThemeService } from '@/app/core/theme.service';
import { isAdminNavActive, isExternalUrl, normalizePathname } from '@/app/core/admin-nav';
import { IconComponent } from '@/app/shared/icon.component';

@Component({
  selector: 'app-admin-shell',
  imports: [RouterOutlet, RouterLink, IconComponent],
  template: `
    <div class="admin-shell admin-main flex h-dvh w-full overflow-hidden">
      <div
        class="hidden shrink-0 transition-[width] duration-300 ease-in-out lg:block"
        [style.width.px]="sidebarWidth()"
        aria-hidden="true"
      ></div>

      <aside
        class="fixed top-0 left-0 z-50 flex h-dvh flex-col border-r border-gray-200 bg-white transition-[width,transform] duration-300 ease-in-out dark:border-gray-800 dark:bg-gray-900"
        [class.translate-x-0]="sidebar.isMobileOpen()"
        [class.-translate-x-full]="!sidebar.isMobileOpen()"
        [class.lg:translate-x-0]="true"
        [style.width.px]="asideWidth()"
        aria-label="Admin navigation"
      >
        <div class="admin-topbar flex items-center gap-3 px-4">
          <a
            routerLink="/admin"
            (click)="sidebar.closeMobileSidebar()"
            class="flex min-w-0 flex-1 items-center gap-3"
            [class.justify-center]="!showLabels()"
          >
            <span
              class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-500 text-base font-bold text-white"
              >{{ brand.letter }}</span
            >
            @if (showLabels()) {
              <div class="min-w-0">
                <p class="truncate text-[15px] font-semibold text-gray-900 dark:text-white">
                  {{ brand.name }}
                </p>
                <p class="truncate text-xs text-gray-500">{{ brand.tagline }}</p>
              </div>
            }
          </a>
          @if (!sidebar.isDesktop()) {
            <button
              type="button"
              class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100 dark:hover:bg-white/10"
              aria-label="Close menu"
              (click)="sidebar.closeMobileSidebar()"
            >
              <app-icon name="x" [size]="20" />
            </button>
          }
        </div>

        <nav class="no-scrollbar flex flex-1 flex-col gap-1 overflow-y-auto px-3 py-5">
          @if (showLabels()) {
            <p
              class="mb-2 px-3 text-[11px] font-semibold tracking-wider text-gray-400 uppercase"
            >
              Menu
            </p>
          }
          @for (item of navItems; track item.href) {
            <a
              [routerLink]="item.href"
              (click)="sidebar.closeMobileSidebar()"
              class="nav-link flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-gray-600 transition hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/5"
              [class.bg-brand-500]="isActive(item.href)"
              [class.text-white]="isActive(item.href)"
              [class.hover:bg-brand-600]="isActive(item.href)"
              [class.dark:bg-brand-500]="isActive(item.href)"
              [title]="item.name"
            >
              <app-icon [name]="item.icon" [size]="22" />
              @if (showLabels()) {
                <span>{{ item.name }}</span>
              }
            </a>
          }
        </nav>

        <div class="sidebar-footer space-y-1 border-t border-gray-100 p-3 dark:border-gray-800">
          @if (externalSite) {
            <a
              [href]="siteUrl"
              class="nav-link flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/5"
            >
              <app-icon name="external-link" [size]="22" />
              @if (showLabels()) {
                <span>View site</span>
              }
            </a>
          } @else {
            <a
              [routerLink]="siteUrl"
              (click)="sidebar.closeMobileSidebar()"
              class="nav-link flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/5"
            >
              <app-icon name="external-link" [size]="22" />
              @if (showLabels()) {
                <span>View site</span>
              }
            </a>
          }
          @if (sidebar.isDesktop()) {
            <button
              type="button"
              class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-white/5"
              [class.justify-center]="!showLabels()"
              (click)="sidebar.toggleSidebar()"
            >
              <app-icon [name]="sidebar.isExpanded() ? 'chevron-left' : 'chevron-right'" [size]="22" />
              @if (showLabels()) {
                <span>Collapse</span>
              }
            </button>
          }
        </div>
      </aside>

      @if (sidebar.isMobileOpen() && !sidebar.isDesktop()) {
        <button
          type="button"
          class="fixed inset-0 z-40 bg-black/40 lg:hidden"
          aria-label="Close menu"
          (click)="sidebar.closeMobileSidebar()"
        ></button>
      }

      <div class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
        <header
          class="admin-topbar sticky top-0 z-30 w-full bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/80 dark:bg-gray-900/95"
        >
          <div class="flex h-full items-center gap-3 px-4 sm:gap-4 sm:px-6">
            <button
              type="button"
              class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-gray-200 text-gray-600 transition hover:bg-gray-50 lg:hidden dark:border-gray-800 dark:text-gray-400"
              aria-label="Open menu"
              (click)="sidebar.toggleMobileSidebar()"
            >
              <app-icon name="menu" [size]="20" />
            </button>

            <a routerLink="/admin" class="flex items-center gap-2 lg:hidden">
              <span
                class="flex h-9 w-9 items-center justify-center rounded-lg bg-brand-500 text-sm font-bold text-white"
                >{{ brand.letter }}</span
              >
              <span class="text-base font-semibold text-gray-900 dark:text-white">{{
                brand.name
              }}</span>
            </a>

            <div class="hidden flex-1 lg:block lg:max-w-lg">
              <label class="relative block">
                <span
                  class="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-gray-400"
                >
                  <app-icon name="search" [size]="16" />
                </span>
                <input
                  type="search"
                  disabled
                  placeholder="Search — connect API to enable"
                  class="h-10 w-full cursor-not-allowed rounded-lg border border-gray-200 bg-gray-50 py-2 pr-4 pl-10 text-sm text-gray-500 placeholder:text-gray-400 dark:border-gray-800 dark:bg-white/5"
                  aria-label="Search"
                />
              </label>
            </div>

            <div class="ml-auto flex items-center gap-2 sm:gap-3">
              <button
                type="button"
                class="flex h-10 items-center gap-2 rounded-lg border border-gray-200 px-3 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:border-gray-800 dark:text-gray-400 dark:hover:bg-white/5"
                aria-label="AI assistant (preview)"
              >
                <app-icon name="panel-right-open" [size]="16" />
                <span class="hidden sm:inline">AI</span>
              </button>

              <button
                type="button"
                class="flex h-10 w-10 items-center justify-center rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 dark:border-gray-800 dark:text-gray-400 dark:hover:bg-white/5"
                [attr.aria-label]="
                  theme.theme() === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'
                "
                (click)="theme.toggle()"
              >
                <app-icon [name]="theme.theme() === 'dark' ? 'sun' : 'moon'" [size]="20" />
              </button>

              <div class="relative flex items-center gap-2">
                <button
                  type="button"
                  class="flex items-center gap-2 rounded-lg border border-gray-200 px-2 py-1.5 hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-white/5"
                  (click)="menuOpen = !menuOpen; $event.stopPropagation()"
                >
                  <span
                    class="flex h-8 w-8 items-center justify-center rounded-full bg-brand-500 text-sm font-semibold text-white"
                    >{{ initials() }}</span
                  >
                  <span class="hidden text-left sm:block">
                    <span class="block text-sm font-medium text-gray-900 dark:text-white">{{
                      auth.admin()?.username
                    }}</span>
                    <span class="block text-xs text-gray-500">{{ auth.admin()?.email }}</span>
                  </span>
                  <app-icon name="chevron-down" [size]="16" class="text-gray-400" />
                </button>
                @if (menuOpen) {
                  <div
                    class="absolute top-full right-0 z-50 mt-2 w-44 rounded-xl border border-gray-200 bg-white p-1 shadow-lg dark:border-gray-800 dark:bg-gray-900"
                    (click)="$event.stopPropagation()"
                  >
                    <button
                      type="button"
                      class="w-full rounded-lg px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-50 dark:text-gray-200 dark:hover:bg-white/5"
                      (click)="signOut()"
                    >
                      Sign out
                    </button>
                  </div>
                }
              </div>
            </div>
          </div>
        </header>

        <main class="admin-scrollbar min-h-0 flex-1 overflow-y-auto overflow-x-hidden">
          <div class="w-full px-4 py-5 sm:px-6 sm:py-6 lg:px-8">
            <router-outlet />
          </div>
        </main>
      </div>
    </div>
  `,
})
export class AdminShellComponent implements OnInit {
  readonly auth = inject(AuthService);
  readonly sidebar = inject(SidebarService);
  readonly theme = inject(ThemeService);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  readonly brand = adminConfig.brand;
  readonly navItems = adminNavItems;
  readonly siteUrl = this.brand.siteUrl || '/';
  readonly externalSite = isExternalUrl(this.siteUrl);
  menuOpen = false;

  private readonly url = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map(() => this.router.url),
      startWith(this.router.url),
    ),
    { initialValue: this.router.url },
  );

  readonly showLabels = computed(
    () => !this.sidebar.isDesktop() || this.sidebar.isExpanded() || this.sidebar.isMobileOpen(),
  );

  readonly sidebarWidth = computed(() =>
    this.sidebar.isDesktop() ? this.sidebar.desktopWidth() : 0,
  );

  ngOnInit(): void {
    this.router.events
      .pipe(
        filter((e): e is NavigationEnd => e instanceof NavigationEnd),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe(() => {
        this.sidebar.closeMobileSidebar();
        this.menuOpen = false;
      });

    const onDocClick = () => {
      if (this.menuOpen) this.menuOpen = false;
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') this.menuOpen = false;
    };
    document.addEventListener('click', onDocClick);
    document.addEventListener('keydown', onKey);
    this.destroyRef.onDestroy(() => {
      document.removeEventListener('click', onDocClick);
      document.removeEventListener('keydown', onKey);
    });
  }

  asideWidth(): number {
    if (this.sidebar.isDesktop()) return this.sidebar.desktopWidth();
    return Math.min(320, SIDEBAR_WIDTH_EXPANDED);
  }

  isActive(href: string): boolean {
    const path = normalizePathname(this.url().split('?')[0] ?? '/');
    return isAdminNavActive(path, href);
  }

  initials(): string {
    return (this.auth.admin()?.username || 'A').charAt(0).toUpperCase();
  }

  signOut(): void {
    this.menuOpen = false;
    this.auth.logout();
    void this.router.navigateByUrl('/admin/login', { replaceUrl: true });
  }

  protected readonly SIDEBAR_WIDTH_COLLAPSED = SIDEBAR_WIDTH_COLLAPSED;
}

// packages/create-zenpanel/templates/vue/src/lib/AdminShell.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import { adminConfig, adminNavItems } from "./config";
import { getAdmin, logout, type AdminSession } from "./auth";
import { getTheme, initTheme, toggleTheme } from "./theme";
import { navigate, normalizePath } from "./router";
import { refreshIcons } from "./icons";

const props = defineProps<{
  pageTitle: string;
}>();

const SIDEBAR_KEY = "zenpanel-sidebar-expanded";
const { brand } = adminConfig;

const admin = ref<AdminSession | null>(null);
const expanded = ref(true);
const mobileOpen = ref(false);
const themeDark = ref(false);
const desktop = ref(false);

function isDesktop() {
  return window.matchMedia("(min-width: 1024px)").matches;
}

function isActive(href: string) {
  const path = normalizePath(window.location.pathname);
  if (href === "/admin") return path === "/admin";
  return path === href;
}

const sidebarWidth = computed(() => {
  if (!desktop.value) return 0;
  return expanded.value ? 260 : 80;
});

const showLabels = computed(
  () => !desktop.value || expanded.value || mobileOpen.value,
);

const sidebarVisible = computed(() => mobileOpen.value || desktop.value);

function go(path: string) {
  return (e: MouseEvent) => {
    e.preventDefault();
    mobileOpen.value = false;
    navigate(path);
  };
}

async function onToggleTheme() {
  toggleTheme();
  themeDark.value = getTheme() === "dark";
  await nextTick();
  refreshIcons();
}

function onToggleSidebar() {
  expanded.value = !expanded.value;
  try {
    localStorage.setItem(SIDEBAR_KEY, expanded.value ? "1" : "0");
  } catch {
    // ignore
  }
}

function onLogout() {
  logout();
  navigate("/admin/login", { replace: true });
}

let mq: MediaQueryList | null = null;
function onMqChange() {
  if (!mq) return;
  desktop.value = mq.matches;
  mobileOpen.value = false;
}

onMounted(async () => {
  initTheme();
  const session = getAdmin();
  if (!session) {
    navigate("/admin/login", { replace: true });
    return;
  }
  admin.value = session;
  themeDark.value = getTheme() === "dark";
  desktop.value = isDesktop();

  try {
    expanded.value = localStorage.getItem(SIDEBAR_KEY) !== "0";
  } catch {
    expanded.value = true;
  }

  mq = window.matchMedia("(min-width: 1024px)");
  mq.addEventListener("change", onMqChange);

  await nextTick();
  refreshIcons();
});

onUnmounted(() => {
  mq?.removeEventListener("change", onMqChange);
});

watch(
  () => [expanded.value, mobileOpen.value, themeDark.value, props.pageTitle],
  async () => {
    await nextTick();
    refreshIcons();
  },
);
</script>

<template>
  <div v-if="admin" class="admin-main">
    <div
      class="admin-sidebar-spacer"
      :style="{ width: `${sidebarWidth}px` }"
      aria-hidden="true"
    ></div>
    <aside
      class="admin-sidebar"
      :class="{
        collapsed: !expanded,
        'mobile-closed': !sidebarVisible,
      }"
      aria-label="Admin navigation"
      :aria-hidden="sidebarVisible ? 'false' : 'true'"
      :inert="!sidebarVisible ? true : undefined"
    >
      <div class="admin-topbar">
        <a
          href="/admin"
          :style="{
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
            minWidth: 0,
            flex: 1,
            justifyContent: showLabels ? undefined : 'center',
          }"
          @click="go('/admin')"
        >
          <span class="brand-mark">{{ brand.letter }}</span>
          <div v-if="showLabels" class="brand-text" style="min-width: 0">
            <div style="font-weight: 600; font-size: 15px">{{ brand.name }}</div>
            <div class="muted" style="font-size: 12px">{{ brand.tagline }}</div>
          </div>
        </a>
        <button
          v-if="!desktop"
          type="button"
          class="icon-btn"
          aria-label="Close menu"
          @click="mobileOpen = false"
        >
          <i data-lucide="x" style="width: 22px; height: 22px; flex-shrink: 0"></i>
        </button>
      </div>
      <nav class="nav-list">
        <p v-if="showLabels" class="nav-label">Menu</p>
        <a
          v-for="item in adminNavItems"
          :key="item.href"
          class="nav-link"
          :class="{ active: isActive(item.href) }"
          :href="item.href"
          :title="item.name"
          @click="go(item.href)"
        >
          <i
            :data-lucide="item.icon"
            style="width: 22px; height: 22px; flex-shrink: 0"
          ></i>
          <span v-if="showLabels" class="nav-text">{{ item.name }}</span>
        </a>
      </nav>
      <div class="sidebar-footer">
        <a
          class="nav-link"
          :href="brand.siteUrl || '/'"
          @click="go(brand.siteUrl || '/')"
        >
          <i
            data-lucide="external-link"
            style="width: 22px; height: 22px; flex-shrink: 0"
          ></i>
          <span v-if="showLabels" class="nav-text">View site</span>
        </a>
        <button
          v-if="desktop"
          type="button"
          class="btn btn-ghost"
          :style="{
            width: '100%',
            justifyContent: showLabels ? 'flex-start' : 'center',
            gap: '0.75rem',
          }"
          @click="onToggleSidebar"
        >
          <template v-if="expanded">
            <i
              data-lucide="chevron-left"
              style="width: 22px; height: 22px; flex-shrink: 0"
            ></i>
            <span>Collapse</span>
          </template>
          <i
            v-else
            data-lucide="chevron-right"
            style="width: 22px; height: 22px; flex-shrink: 0"
          ></i>
        </button>
      </div>
    </aside>
    <button
      type="button"
      class="backdrop"
      aria-label="Close menu"
      :hidden="!(mobileOpen && !desktop)"
      @click="mobileOpen = false"
    ></button>
    <div class="admin-content-wrap">
      <header class="admin-header">
        <div style="display: flex; align-items: center; gap: 0.75rem">
          <button
            type="button"
            class="icon-btn hidden-desktop"
            aria-label="Open menu"
            @click="mobileOpen = true"
          >
            <i
              data-lucide="menu"
              style="width: 22px; height: 22px; flex-shrink: 0"
            ></i>
          </button>
          <strong style="font-size: 0.95rem">{{ pageTitle }}</strong>
        </div>
        <div style="display: flex; align-items: center; gap: 0.5rem">
          <button
            type="button"
            class="icon-btn"
            :aria-label="
              themeDark ? 'Switch to light mode' : 'Switch to dark mode'
            "
            @click="onToggleTheme"
          >
            <i
              :data-lucide="themeDark ? 'sun' : 'moon'"
              style="width: 22px; height: 22px; flex-shrink: 0"
            ></i>
          </button>
          <div class="user-chip">
            <span class="user-avatar">{{
              (admin.username || "A").charAt(0).toUpperCase()
            }}</span>
            <div
              class="only-desktop"
              style="
                flex-direction: column;
                align-items: flex-start;
                line-height: 1.2;
              "
            >
              <span style="font-size: 0.875rem; font-weight: 500">{{
                admin.username
              }}</span>
              <span class="muted" style="font-size: 0.75rem">{{
                admin.email
              }}</span>
            </div>
            <button
              type="button"
              class="btn btn-ghost"
              style="height: 2rem; padding: 0 0.75rem"
              @click="onLogout"
            >
              Sign out
            </button>
          </div>
        </div>
      </header>
      <main class="admin-main-scroll">
        <slot />
      </main>
    </div>
  </div>
</template>
