// packages/create-zenpanel/templates/solid/src/components/admin/chat/admin-chat-markdown.tsx
import { createMemo, For } from "solid-js";

type Props = {
  content: string;
};

/** Lightweight assistant text — supports **bold** and line breaks without extra deps. */
export function AdminChatMarkdown(props: Props) {
  const parts = createMemo(() => props.content.split(/(\*\*[^*]+\*\*)/g));

  return (
    <div class="admin-chat-markdown text-sm leading-relaxed">
      <For each={parts()}>
        {(part) => {
          if (part.startsWith("**") && part.endsWith("**")) {
            return <strong class="font-semibold">{part.slice(2, -2)}</strong>;
          }

          const lines = part.split("\n");
          return (
            <For each={lines}>
              {(line, j) => (
                <span>
                  {line}
                  {j() < lines.length - 1 ? <br /> : null}
                </span>
              )}
            </For>
          );
        }}
      </For>
    </div>
  );
}

// packages/create-zenpanel/templates/preact/src/components/admin/chat/admin-chat-markdown.tsx
type Props = {
  content: string;
};

/** Lightweight assistant text — supports **bold** and line breaks without extra deps. */
export function AdminChatMarkdown({ content }: Props) {
  const parts = content.split(/(\*\*[^*]+\*\*)/g);

  return (
    <div className="admin-chat-markdown text-sm leading-relaxed">
      {parts.map((part, i) => {
        if (part.startsWith("**") && part.endsWith("**")) {
          return (
            <strong key={i} className="font-semibold">
              {part.slice(2, -2)}
            </strong>
          );
        }

        return part.split("\n").map((line, j, arr) => (
          <span key={`${i}-${j}`}>
            {line}
            {j < arr.length - 1 ? <br /> : null}
          </span>
        ));
      })}
    </div>
  );
}
