// packages/create-zenpanel/templates/svelte/src/components/admin/auth/AdminGuestGuard.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { useAdminAuth } from "@/context/admin-auth-context.svelte";
  import { navigate } from "@/lib/router.svelte";
  import AdminLoading from "@/components/admin/ui/AdminLoading.svelte";

  type Props = { children?: Snippet };
  let { children }: Props = $props();

  const auth = useAdminAuth();

  $effect(() => {
    if (!auth.loading && auth.admin) {
      navigate("/admin", { replace: true });
    }
  });
</script>

{#if !auth.loading && !auth.admin}
  {@render children?.()}
{:else}
  <AdminLoading message={auth.loading ? "Loading…" : "Redirecting to dashboard…"} fullHeight />
{/if}

// packages/create-zenpanel/templates/react/src/components/admin/auth/admin-guest-guard.tsx
import { useAdminAuth } from "@/components/admin/auth/admin-auth-provider";
import { AdminLoading } from "@/components/admin/ui/admin-loading";
import { useNavigate } from "react-router-dom";
import { useEffect } from "react";

/** Redirects authenticated admins away from login (and other guest-only routes). */
export function AdminGuestGuard({ children }: { children: React.ReactNode }) {
  const { admin, loading } = useAdminAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && admin) {
      navigate("/admin", { replace: true });
    }
  }, [admin, loading, navigate]);

  if (loading) {
    return <AdminLoading message="Loading…" fullHeight />;
  }

  if (admin) {
    return <AdminLoading message="Redirecting to dashboard…" fullHeight />;
  }

  return <>{children}</>;
}
