// packages/create-zenpanel/templates/svelte/src/components/theme/ThemeProvider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { createTheme } from "@/context/theme-context.svelte";

  type Props = {
    children?: Snippet;
    defaultTheme?: "light" | "dark" | "system";
    enableSystem?: boolean;
    disableTransitionOnChange?: boolean;
  };

  let {
    children,
    defaultTheme = "light",
    enableSystem = true,
    disableTransitionOnChange = false,
  }: Props = $props();

  createTheme({
    get defaultTheme() {
      return defaultTheme;
    },
    get enableSystem() {
      return enableSystem;
    },
    get disableTransitionOnChange() {
      return disableTransitionOnChange;
    },
  });
</script>

{@render children?.()}

// packages/create-zenpanel/templates/react/src/components/theme/theme-provider.tsx
import type { ReactNode } from "react";
import { ThemeProvider as NextThemesProvider } from "next-themes";

export function ThemeProvider({ children }: { children: ReactNode }) {
  return (
    <NextThemesProvider
      attribute="class"
      defaultTheme="light"
      enableSystem
      disableTransitionOnChange
    >
      {children}
    </NextThemesProvider>
  );
}
