// packages/create-zenpanel/templates/svelte/src/components/theme/ThemeProvider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { createTheme } from "@/context/theme-context.svelte";

  type Props = {
    children?: Snippet;
    defaultTheme?: "light" | "dark" | "system";
    enableSystem?: boolean;
    disableTransitionOnChange?: boolean;
  };

  let {
    children,
    defaultTheme = "light",
    enableSystem = true,
    disableTransitionOnChange = false,
  }: Props = $props();

  createTheme({
    get defaultTheme() {
      return defaultTheme;
    },
    get enableSystem() {
      return enableSystem;
    },
    get disableTransitionOnChange() {
      return disableTransitionOnChange;
    },
  });
</script>

{@render children?.()}

// packages/create-zenpanel/templates/vue/src/components/theme/ThemeProvider.vue
<script setup lang="ts">
import { provideTheme } from "@/composables/use-theme";

const props = withDefaults(
  defineProps<{
    defaultTheme?: "light" | "dark" | "system";
    enableSystem?: boolean;
    disableTransitionOnChange?: boolean;
  }>(),
  {
    defaultTheme: "light",
    enableSystem: true,
    disableTransitionOnChange: false,
  },
);

provideTheme({
  defaultTheme: props.defaultTheme,
  enableSystem: props.enableSystem,
  disableTransitionOnChange: props.disableTransitionOnChange,
});
</script>

<template>
  <slot />
</template>
