// packages/create-zenpanel/templates/solid/src/components/admin/layout/admin-sidebar.tsx
import { adminConfig, adminNavItems } from "@/config/admin.config";
import {
  SIDEBAR_WIDTH_COLLAPSED,
  SIDEBAR_WIDTH_EXPANDED,
  useAdminSidebar,
} from "@/context/admin-sidebar-context";
import { isAdminNavActive, isExternalUrl } from "@/lib/admin-nav";
import { ChevronLeft, ChevronRight, ExternalLink, X } from "lucide-solid";
import { A, useLocation } from "@solidjs/router";
import { createEffect, createMemo, For, Show } from "solid-js";

export function AdminSidebar() {
  const location = useLocation();
  const { isExpanded, isMobileOpen, isDesktop, toggleSidebar, closeMobileSidebar } =
    useAdminSidebar();

  createEffect(() => {
    location.pathname;
    closeMobileSidebar();
  });

  const showLabels = createMemo(() => !isDesktop() || isExpanded() || isMobileOpen());
  const desktopWidth = createMemo(() =>
    isExpanded() ? SIDEBAR_WIDTH_EXPANDED : SIDEBAR_WIDTH_COLLAPSED,
  );
  const mobileClosed = createMemo(() => !isDesktop() && !isMobileOpen());
  const { brand } = adminConfig;
  const siteUrl = brand.siteUrl || "/";

  return (
    <aside
      style={{
        width: isDesktop() ? `${desktopWidth()}px` : `${Math.min(320, SIDEBAR_WIDTH_EXPANDED)}px`,
      }}
      class={`fixed top-0 left-0 z-50 flex h-dvh flex-col border-r border-gray-200 bg-white transition-[width,transform] duration-300 ease-in-out dark:border-gray-800 dark:bg-gray-900 ${
        isMobileOpen() ? "translate-x-0" : "-translate-x-full"
      } lg:translate-x-0`}
      aria-label="Admin navigation"
      aria-hidden={mobileClosed() || undefined}
      inert={mobileClosed() || undefined}
    >
      <div class="admin-topbar flex items-center gap-3 px-4">
        <A
          href="/admin"
          onClick={closeMobileSidebar}
          class={`flex min-w-0 flex-1 items-center gap-3 ${!showLabels() ? "justify-center" : ""}`}
        >
          <span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-500 text-base font-bold text-white">
            {brand.letter}
          </span>
          <Show when={showLabels()}>
            <div class="min-w-0">
              <p class="truncate text-[15px] font-semibold text-gray-900 dark:text-white">
                {brand.name}
              </p>
              <p class="truncate text-xs text-gray-500">{brand.tagline}</p>
            </div>
          </Show>
        </A>
        <Show when={!isDesktop()}>
          <button
            type="button"
            onClick={closeMobileSidebar}
            class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100 dark:hover:bg-white/10"
            aria-label="Close menu"
          >
            <X class="h-5 w-5" />
          </button>
        </Show>
      </div>

      <nav class="no-scrollbar flex flex-1 flex-col gap-1 overflow-y-auto px-3 py-5">
        <Show when={showLabels()}>
          <p class="mb-2 px-3 text-[11px] font-semibold tracking-wider text-gray-400 uppercase">
            Menu
          </p>
        </Show>
        <For each={adminNavItems}>
          {(item) => {
            const active = createMemo(() => isAdminNavActive(location.pathname, item.href));
            const Icon = item.icon;

            return (
              <A
                href={item.href}
                onClick={closeMobileSidebar}
                title={!showLabels() ? item.name : undefined}
                aria-current={active() ? "page" : undefined}
                class={`group relative flex items-center gap-3 rounded-xl px-3 py-3 text-[15px] font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/40 ${
                  active()
                    ? "bg-brand-500 text-white shadow-md shadow-brand-500/25"
                    : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-white/8"
                } ${!showLabels() ? "justify-center px-0" : ""}`}
              >
                <Icon
                  class={`h-[22px] w-[22px] shrink-0 ${
                    active()
                      ? "text-white"
                      : "text-gray-500 group-hover:text-gray-700 dark:text-gray-400"
                  }`}
                />
                <Show when={showLabels()}>
                  <span class="truncate">{item.name}</span>
                </Show>
              </A>
            );
          }}
        </For>
      </nav>

      <div class="shrink-0 space-y-1 border-t border-gray-200 p-3 dark:border-gray-800">
        <Show
          when={isExternalUrl(siteUrl)}
          fallback={
            <A
              href={siteUrl}
              class={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/8 ${!showLabels() ? "justify-center" : ""}`}
              title={!showLabels() ? "View site" : undefined}
            >
              <ExternalLink class="h-5 w-5 shrink-0" />
              <Show when={showLabels()}>
                <span>View site</span>
              </Show>
            </A>
          }
        >
          <a
            href={siteUrl}
            target="_blank"
            rel="noreferrer"
            class={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/8 ${!showLabels() ? "justify-center" : ""}`}
            title={!showLabels() ? "View site" : undefined}
          >
            <ExternalLink class="h-5 w-5 shrink-0" />
            <Show when={showLabels()}>
              <span>View site</span>
            </Show>
          </a>
        </Show>

        <Show when={isDesktop()}>
          <button
            type="button"
            onClick={toggleSidebar}
            class={`mt-2 flex w-full items-center gap-3 rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-white/5 ${!showLabels() ? "justify-center" : ""}`}
            aria-label={isExpanded() ? "Collapse sidebar" : "Expand sidebar"}
          >
            <Show when={isExpanded()} fallback={<ChevronRight class="h-5 w-5 shrink-0" />}>
              <ChevronLeft class="h-5 w-5 shrink-0" />
              <span>Collapse</span>
            </Show>
          </button>
        </Show>
      </div>
    </aside>
  );
}

// packages/create-zenpanel/templates/vite/src/components/admin/layout/admin-sidebar.tsx
import { adminConfig, adminNavItems } from "@/config/admin.config";
import {
  SIDEBAR_WIDTH_COLLAPSED,
  SIDEBAR_WIDTH_EXPANDED,
  useAdminSidebar,
} from "@/context/admin-sidebar-context";
import { isAdminNavActive, isExternalUrl } from "@/lib/admin-nav";
import { ChevronLeft, ChevronRight, ExternalLink, X } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { useEffect } from "react";

export function AdminSidebar() {
  const { pathname } = useLocation();
  const {
    isExpanded,
    isMobileOpen,
    isDesktop,
    toggleSidebar,
    closeMobileSidebar,
  } = useAdminSidebar();

  useEffect(() => {
    closeMobileSidebar();
  }, [pathname, closeMobileSidebar]);

  const showLabels = !isDesktop || isExpanded || isMobileOpen;
  const desktopWidth = isExpanded ? SIDEBAR_WIDTH_EXPANDED : SIDEBAR_WIDTH_COLLAPSED;
  const { brand } = adminConfig;
  const siteUrl = brand.siteUrl || "/";
  const mobileClosed = !isDesktop && !isMobileOpen;

  return (
    <aside
      style={
        isDesktop
          ? { width: desktopWidth }
          : { width: Math.min(320, SIDEBAR_WIDTH_EXPANDED) }
      }
      className={`fixed top-0 left-0 z-50 flex h-dvh flex-col border-r border-gray-200 bg-white transition-[width,transform] duration-300 ease-in-out dark:border-gray-800 dark:bg-gray-900 ${
        isMobileOpen ? "translate-x-0" : "-translate-x-full"
      } lg:translate-x-0`}
      aria-label="Admin navigation"
      aria-hidden={mobileClosed || undefined}
      inert={mobileClosed || undefined}
    >
      <div className="admin-topbar flex items-center gap-3 px-4">
        <Link
          to="/admin"
          onClick={closeMobileSidebar}
          className={`flex min-w-0 flex-1 items-center gap-3 ${!showLabels ? "justify-center" : ""}`}
        >
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-500 text-base font-bold text-white">
            {brand.letter}
          </span>
          {showLabels && (
            <div className="min-w-0">
              <p className="truncate text-[15px] font-semibold text-gray-900 dark:text-white">
                {brand.name}
              </p>
              <p className="truncate text-xs text-gray-500">{brand.tagline}</p>
            </div>
          )}
        </Link>
        {!isDesktop && (
          <button
            type="button"
            onClick={closeMobileSidebar}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100 dark:hover:bg-white/10"
            aria-label="Close menu"
          >
            <X className="h-5 w-5" />
          </button>
        )}
      </div>

      <nav className="no-scrollbar flex flex-1 flex-col gap-1 overflow-y-auto px-3 py-5">
        {showLabels && (
          <p className="mb-2 px-3 text-[11px] font-semibold tracking-wider text-gray-400 uppercase">
            Menu
          </p>
        )}
        {adminNavItems.map((item) => {
          const active = isAdminNavActive(pathname, item.href);
          const Icon = item.icon;

          return (
            <Link
              key={item.href}
              to={item.href}
              onClick={closeMobileSidebar}
              title={!showLabels ? item.name : undefined}
              aria-current={active ? "page" : undefined}
              className={`group relative flex items-center gap-3 rounded-xl px-3 py-3 text-[15px] font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/40 ${
                active
                  ? "bg-brand-500 text-white shadow-md shadow-brand-500/25"
                  : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-white/8"
              } ${!showLabels ? "justify-center px-0" : ""}`}
            >
              <Icon
                className={`h-[22px] w-[22px] shrink-0 ${
                  active
                    ? "text-white"
                    : "text-gray-500 group-hover:text-gray-700 dark:text-gray-400"
                }`}
              />
              {showLabels && <span className="truncate">{item.name}</span>}
            </Link>
          );
        })}
      </nav>

      <div className="shrink-0 space-y-1 border-t border-gray-200 p-3 dark:border-gray-800">
        {isExternalUrl(siteUrl) ? (
          <a
            href={siteUrl}
            target="_blank"
            rel="noreferrer"
            className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/8 ${!showLabels ? "justify-center" : ""}`}
            title={!showLabels ? "View site" : undefined}
          >
            <ExternalLink className="h-5 w-5 shrink-0" />
            {showLabels && <span>View site</span>}
          </a>
        ) : (
          <Link
            to={siteUrl}
            className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/8 ${!showLabels ? "justify-center" : ""}`}
            title={!showLabels ? "View site" : undefined}
          >
            <ExternalLink className="h-5 w-5 shrink-0" />
            {showLabels && <span>View site</span>}
          </Link>
        )}

        {isDesktop && (
          <button
            type="button"
            onClick={toggleSidebar}
            className={`mt-2 flex w-full items-center gap-3 rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-white/5 ${!showLabels ? "justify-center" : ""}`}
            aria-label={isExpanded ? "Collapse sidebar" : "Expand sidebar"}
          >
            {isExpanded ? (
              <>
                <ChevronLeft className="h-5 w-5 shrink-0" />
                <span>Collapse</span>
              </>
            ) : (
              <ChevronRight className="h-5 w-5 shrink-0" />
            )}
          </button>
        )}
      </div>
    </aside>
  );
}
