// packages/create-zenpanel/templates/svelte/src/components/admin/shared/ResourceList.svelte
<script lang="ts">
  import AdminEmptyState from "@/components/admin/ui/AdminEmptyState.svelte";
  import type { AdminResource } from "@/lib/admin-data/resources";
  import { Database, MoreHorizontal, Pencil, Plus, Trash2 } from "lucide-svelte";

  const statusStyles: Record<AdminResource["status"], string> = {
    published: "bg-success-50 text-success-600 dark:bg-success-500/15 dark:text-success-500",
    draft: "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400",
    archived: "bg-orange-50 text-orange-700 dark:bg-orange-500/15 dark:text-orange-400",
  };

  const disabledActionTitle = "Available after you connect your API";

  const irregularPlurals: Record<string, string> = {
    category: "categories",
  };

  function pluralize(label: string, count: number): string {
    if (count === 1) return label;
    return irregularPlurals[label] ?? `${label}s`;
  }

  type Props = {
    items: AdminResource[];
    resourceLabel: string;
  };

  let { items, resourceLabel }: Props = $props();
</script>

<div class="admin-card w-full overflow-hidden">
  <div class="flex flex-col gap-3 border-b border-gray-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6 dark:border-gray-800">
    <div>
      <p class="text-sm font-medium text-gray-700 dark:text-gray-300">
        {items.length} {pluralize(resourceLabel, items.length)}
      </p>
      <p class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">
        UI shell — wire your API to enable create, edit, and delete.
      </p>
    </div>
    <button
      type="button"
      disabled
      title={disabledActionTitle}
      class="inline-flex h-9 cursor-not-allowed items-center justify-center gap-2 rounded-lg bg-brand-500/50 px-4 text-sm font-semibold text-white/90"
    >
      <Plus class="h-4 w-4" aria-hidden={true} />
      Add new
    </button>
  </div>

  {#if items.length > 0}
    <div class="admin-scrollbar overflow-x-auto">
      <table class="w-full min-w-[720px] text-left text-sm">
        <thead>
          <tr class="border-b border-gray-200 bg-gray-50/80 dark:border-gray-800 dark:bg-white/[0.02]">
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">Title</th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">Status</th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">Details</th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">Updated</th>
            <th scope="col" class="px-6 py-3.5 text-right text-xs font-semibold tracking-wide text-gray-500 uppercase">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 dark:divide-gray-800">
          {#each items as item (item.id)}
            <tr class="transition-colors hover:bg-gray-50/80 dark:hover:bg-white/[0.02]">
              <td class="px-6 py-4 font-medium text-gray-900 dark:text-white/90">{item.title}</td>
              <td class="px-6 py-4">
                <span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium capitalize {statusStyles[item.status]}">
                  {item.status}
                </span>
              </td>
              <td class="px-6 py-4 text-gray-500">{item.meta ?? "—"}</td>
              <td class="px-6 py-4 whitespace-nowrap text-gray-500">
                {new Date(item.updatedAt).toLocaleDateString()}
              </td>
              <td class="px-6 py-4">
                <div class="flex items-center justify-end gap-1">
                  <button type="button" disabled title={disabledActionTitle} class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400" aria-label="Edit {item.title}">
                    <Pencil class="h-4 w-4" />
                  </button>
                  <button type="button" disabled title={disabledActionTitle} class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400" aria-label="More actions for {item.title}">
                    <MoreHorizontal class="h-4 w-4" />
                  </button>
                  <button type="button" disabled title={disabledActionTitle} class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400" aria-label="Delete {item.title}">
                    <Trash2 class="h-4 w-4" />
                  </button>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {:else}
    <AdminEmptyState
      icon={Database}
      title="No {resourceLabel.toLowerCase()} yet"
      description="This page is ready for your data. Connect your backend API to load, create, and manage {resourceLabel.toLowerCase()} from here."
    />
  {/if}
</div>

// packages/create-zenpanel/templates/vue/src/components/admin/shared/ResourceList.vue
<script setup lang="ts">
import AdminEmptyState from "@/components/admin/ui/AdminEmptyState.vue";
import type { AdminResource } from "@/lib/admin-data/resources";
import { Database, MoreHorizontal, Pencil, Plus, Trash2 } from "lucide-vue-next";

const statusStyles: Record<AdminResource["status"], string> = {
  published: "bg-success-50 text-success-600 dark:bg-success-500/15 dark:text-success-500",
  draft: "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400",
  archived: "bg-orange-50 text-orange-700 dark:bg-orange-500/15 dark:text-orange-400",
};

const disabledActionTitle = "Available after you connect your API";

const irregularPlurals: Record<string, string> = {
  category: "categories",
};

function pluralize(label: string, count: number): string {
  if (count === 1) return label;
  return irregularPlurals[label] ?? `${label}s`;
}

defineProps<{
  items: AdminResource[];
  resourceLabel: string;
}>();
</script>

<template>
  <div class="admin-card w-full overflow-hidden">
    <div
      class="flex flex-col gap-3 border-b border-gray-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6 dark:border-gray-800"
    >
      <div>
        <p class="text-sm font-medium text-gray-700 dark:text-gray-300">
          {{ items.length }} {{ pluralize(resourceLabel, items.length) }}
        </p>
        <p class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">
          UI shell — wire your API to enable create, edit, and delete.
        </p>
      </div>
      <button
        type="button"
        disabled
        :title="disabledActionTitle"
        class="inline-flex h-9 cursor-not-allowed items-center justify-center gap-2 rounded-lg bg-brand-500/50 px-4 text-sm font-semibold text-white/90"
      >
        <Plus class="h-4 w-4" aria-hidden="true" />
        Add new
      </button>
    </div>

    <div v-if="items.length > 0" class="admin-scrollbar overflow-x-auto">
      <table class="w-full min-w-[720px] text-left text-sm">
        <thead>
          <tr class="border-b border-gray-200 bg-gray-50/80 dark:border-gray-800 dark:bg-white/[0.02]">
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">
              Title
            </th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">
              Status
            </th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">
              Details
            </th>
            <th scope="col" class="px-6 py-3.5 text-xs font-semibold tracking-wide text-gray-500 uppercase">
              Updated
            </th>
            <th scope="col" class="px-6 py-3.5 text-right text-xs font-semibold tracking-wide text-gray-500 uppercase">
              Actions
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 dark:divide-gray-800">
          <tr
            v-for="item in items"
            :key="item.id"
            class="transition-colors hover:bg-gray-50/80 dark:hover:bg-white/[0.02]"
          >
            <td class="px-6 py-4 font-medium text-gray-900 dark:text-white/90">{{ item.title }}</td>
            <td class="px-6 py-4">
              <span
                :class="[
                  'inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium capitalize',
                  statusStyles[item.status],
                ]"
              >
                {{ item.status }}
              </span>
            </td>
            <td class="px-6 py-4 text-gray-500">{{ item.meta ?? "—" }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-gray-500">
              {{ new Date(item.updatedAt).toLocaleDateString() }}
            </td>
            <td class="px-6 py-4">
              <div class="flex items-center justify-end gap-1">
                <button
                  type="button"
                  disabled
                  :title="disabledActionTitle"
                  class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400"
                  :aria-label="`Edit ${item.title}`"
                >
                  <Pencil class="h-4 w-4" />
                </button>
                <button
                  type="button"
                  disabled
                  :title="disabledActionTitle"
                  class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400"
                  :aria-label="`More actions for ${item.title}`"
                >
                  <MoreHorizontal class="h-4 w-4" />
                </button>
                <button
                  type="button"
                  disabled
                  :title="disabledActionTitle"
                  class="flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-lg text-gray-400"
                  :aria-label="`Delete ${item.title}`"
                >
                  <Trash2 class="h-4 w-4" />
                </button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <AdminEmptyState
      v-else
      :icon="Database"
      :title="`No ${resourceLabel.toLowerCase()} yet`"
      :description="`This page is ready for your data. Connect your backend API to load, create, and manage ${resourceLabel.toLowerCase()} from here.`"
    />
  </div>
</template>
