// packages/create-zenpanel/templates/svelte/src/App.svelte
<script lang="ts">
  import ThemeProvider from "@/components/theme/ThemeProvider.svelte";
  import HomePage from "@/pages/HomePage.svelte";
  import AdminRootLayout from "@/layouts/AdminRootLayout.svelte";
  import AdminAuthLayout from "@/layouts/AdminAuthLayout.svelte";
  import AdminDashboardLayout from "@/layouts/AdminDashboardLayout.svelte";
  import LoginPage from "@/pages/admin/LoginPage.svelte";
  import DashboardPage from "@/pages/admin/DashboardPage.svelte";
  import ProjectsPage from "@/pages/admin/ProjectsPage.svelte";
  import ServicesPage from "@/pages/admin/ServicesPage.svelte";
  import ServiceOrdersPage from "@/pages/admin/ServiceOrdersPage.svelte";
  import TransactionsPage from "@/pages/admin/TransactionsPage.svelte";
  import PaymentsPage from "@/pages/admin/PaymentsPage.svelte";
  import BlogPage from "@/pages/admin/BlogPage.svelte";
  import ProductsPage from "@/pages/admin/ProductsPage.svelte";
  import CategoriesPage from "@/pages/admin/CategoriesPage.svelte";
  import MessagesPage from "@/pages/admin/MessagesPage.svelte";
  import NewsletterPage from "@/pages/admin/NewsletterPage.svelte";
  import UsersPage from "@/pages/admin/UsersPage.svelte";
  import SettingsPage from "@/pages/admin/SettingsPage.svelte";
  import { navigate, usePathname } from "@/lib/router.svelte";

  const pathname = usePathname();
  const route = $derived(pathname.route);

  $effect(() => {
    if (route.id === "not-found") {
      navigate("/", { replace: true });
    }
  });
</script>

<ThemeProvider>
  {#if route.id === "home"}
    <HomePage />
  {:else if route.id === "admin-login"}
    <AdminRootLayout>
      <AdminAuthLayout>
        <LoginPage />
      </AdminAuthLayout>
    </AdminRootLayout>
  {:else if route.id.startsWith("admin-")}
    <AdminRootLayout>
      <AdminDashboardLayout>
        {#if route.id === "admin-dashboard"}
          <DashboardPage />
        {:else if route.id === "admin-projects"}
          <ProjectsPage />
        {:else if route.id === "admin-services"}
          <ServicesPage />
        {:else if route.id === "admin-service-orders"}
          <ServiceOrdersPage />
        {:else if route.id === "admin-transactions"}
          <TransactionsPage />
        {:else if route.id === "admin-payments"}
          <PaymentsPage />
        {:else if route.id === "admin-blog"}
          <BlogPage />
        {:else if route.id === "admin-products"}
          <ProductsPage />
        {:else if route.id === "admin-categories"}
          <CategoriesPage />
        {:else if route.id === "admin-messages"}
          <div class="flex h-full min-h-0 flex-1 flex-col">
            <MessagesPage />
          </div>
        {:else if route.id === "admin-newsletter"}
          <NewsletterPage />
        {:else if route.id === "admin-users"}
          <UsersPage />
        {:else if route.id === "admin-settings"}
          <SettingsPage />
        {/if}
      </AdminDashboardLayout>
    </AdminRootLayout>
  {/if}
</ThemeProvider>

// packages/create-zenpanel/templates/vite/src/App.tsx
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AdminAuthLayout } from "@/layouts/AdminAuthLayout";
import { AdminDashboardLayout } from "@/layouts/AdminDashboardLayout";
import { AdminRootLayout } from "@/layouts/AdminRootLayout";
import HomePage from "@/pages/HomePage";
import BlogPage from "@/pages/admin/BlogPage";
import CategoriesPage from "@/pages/admin/CategoriesPage";
import DashboardPage from "@/pages/admin/DashboardPage";
import LoginPage from "@/pages/admin/LoginPage";
import MessagesPage from "@/pages/admin/MessagesPage";
import NewsletterPage from "@/pages/admin/NewsletterPage";
import PaymentsPage from "@/pages/admin/PaymentsPage";
import ProductsPage from "@/pages/admin/ProductsPage";
import ProjectsPage from "@/pages/admin/ProjectsPage";
import ServiceOrdersPage from "@/pages/admin/ServiceOrdersPage";
import ServicesPage from "@/pages/admin/ServicesPage";
import SettingsPage from "@/pages/admin/SettingsPage";
import TransactionsPage from "@/pages/admin/TransactionsPage";
import UsersPage from "@/pages/admin/UsersPage";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";

export default function App() {
  return (
    <ThemeProvider>
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<HomePage />} />

          <Route path="/admin" element={<AdminRootLayout />}>
            <Route element={<AdminAuthLayout />}>
              <Route path="login" element={<LoginPage />} />
            </Route>

            <Route element={<AdminDashboardLayout />}>
              <Route index element={<DashboardPage />} />
              <Route path="projects" element={<ProjectsPage />} />
              <Route path="services" element={<ServicesPage />} />
              <Route path="service-orders" element={<ServiceOrdersPage />} />
              <Route path="transactions" element={<TransactionsPage />} />
              <Route path="payments" element={<PaymentsPage />} />
              <Route path="blog" element={<BlogPage />} />
              <Route path="products" element={<ProductsPage />} />
              <Route path="categories" element={<CategoriesPage />} />
              <Route
                path="messages"
                element={
                  <div className="flex h-full min-h-0 flex-1 flex-col">
                    <MessagesPage />
                  </div>
                }
              />
              <Route path="newsletter" element={<NewsletterPage />} />
              <Route path="users" element={<UsersPage />} />
              <Route path="settings" element={<SettingsPage />} />
            </Route>
          </Route>

          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
}
