// packages/create-zenpanel/templates/svelte/src/pages/admin/UsersPage.svelte
<script lang="ts">
  import AdminUsersPage from "@/components/admin/users/AdminUsersPage.svelte";
  import AdminLoading from "@/components/admin/ui/AdminLoading.svelte";
  import { previewFetchUsers, type PortalUserRow } from "@/lib/admin-api";

  let users = $state<PortalUserRow[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  $effect(() => {
    loading = true;
    error = null;
    previewFetchUsers()
      .then((res) => {
        users = res.users;
      })
      .catch((err) => {
        error = err instanceof Error ? err.message : "Failed to load users";
      })
      .finally(() => {
        loading = false;
      });
  });
</script>

{#if loading}
  <AdminLoading message="Loading users…" />
{:else if error}
  <div class="admin-content">
    <div class="admin-card admin-card-body text-sm text-error-500">
      {error}
    </div>
  </div>
{:else}
  <AdminUsersPage {users} />
{/if}

// demo/src/pages/admin/UsersPage.tsx
import { AdminUsersPage } from "@/components/admin/users/admin-users-page";
import { AdminLoading } from "@/components/admin/ui/admin-loading";
import { previewFetchUsers, type PortalUserRow } from "@/lib/admin-api";
import { useEffect, useState } from "react";

export default function UsersPage() {
  const [users, setUsers] = useState<PortalUserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    previewFetchUsers()
      .then((res) => {
        if (!cancelled) setUsers(res.users);
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load users");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return <AdminLoading message="Loading users…" />;
  }

  if (error) {
    return (
      <div className="admin-content">
        <div className="admin-card admin-card-body text-sm text-error-500">{error}</div>
      </div>
    );
  }

  return <AdminUsersPage users={users} />;
}
