// packages/create-zenpanel/templates/svelte/src/routes/ResourcePage.svelte
<script lang="ts">
  import { resourceSamples } from "../lib/data";

  let {
    title,
    resourceKey,
  }: {
    title: string;
    resourceKey: string;
  } = $props();

  const items = $derived(resourceSamples[resourceKey] ?? []);
</script>

<h1 class="page-title">{title}</h1>
<div class="admin-card">
  <div
    style="padding:1rem 1.25rem;border-bottom:1px solid var(--gray-200);font-weight:600;font-size:0.875rem"
  >
    {title}
  </div>
  {#if items.length}
    <ul style="list-style:none;margin:0;padding:0">
      {#each items as item}
        <li
          style="padding:0.875rem 1.25rem;border-bottom:1px solid var(--gray-100);font-size:0.875rem"
        >
          {item}
        </li>
      {/each}
    </ul>
  {:else}
    <p
      class="muted"
      style="padding:2.5rem 1.25rem;text-align:center;font-size:0.875rem"
    >
      No {title.toLowerCase()} yet.
    </p>
  {/if}
</div>

// packages/create-zenpanel/templates/vue/src/routes/ResourcePage.vue
<script setup lang="ts">
import { computed } from "vue";
import { resourceSamples } from "../lib/data";

const props = defineProps<{
  title: string;
  resourceKey: string;
}>();

const items = computed(() => resourceSamples[props.resourceKey] ?? []);
</script>

<template>
  <h1 class="page-title">{{ title }}</h1>
  <div class="admin-card">
    <div
      style="
        padding: 1rem 1.25rem;
        border-bottom: 1px solid var(--gray-200);
        font-weight: 600;
        font-size: 0.875rem;
      "
    >
      {{ title }}
    </div>
    <ul v-if="items.length" style="list-style: none; margin: 0; padding: 0">
      <li
        v-for="item in items"
        :key="item"
        style="
          padding: 0.875rem 1.25rem;
          border-bottom: 1px solid var(--gray-100);
          font-size: 0.875rem;
        "
      >
        {{ item }}
      </li>
    </ul>
    <p
      v-else
      class="muted"
      style="padding: 2.5rem 1.25rem; text-align: center; font-size: 0.875rem"
    >
      No {{ title.toLowerCase() }} yet.
    </p>
  </div>
</template>
