// packages/create-zenpanel/templates/svelte/src/routes/SettingsPage.svelte
<h1 class="page-title">Settings</h1>
<div class="admin-card admin-card-body">
  <h3 style="margin:0 0 0.5rem;font-size:1rem">Branding &amp; navigation</h3>
  <p class="muted" style="margin:0;font-size:0.875rem;line-height:1.5">
    Edit
    <code
      style="background:var(--gray-100);padding:0.125rem 0.375rem;border-radius:0.25rem;font-size:0.75rem"
      >src/lib/config.ts</code
    >
    to customize the panel name, logo letter, sidebar links, and login page copy.
  </p>
</div>

// packages/create-zenpanel/templates/vue/src/routes/SettingsPage.vue
<template>
  <h1 class="page-title">Settings</h1>
  <div class="admin-card admin-card-body">
    <h3 style="margin: 0 0 0.5rem; font-size: 1rem">
      Branding &amp; navigation
    </h3>
    <p class="muted" style="margin: 0; font-size: 0.875rem; line-height: 1.5">
      Edit
      <code
        style="
          background: var(--gray-100);
          padding: 0.125rem 0.375rem;
          border-radius: 0.25rem;
          font-size: 0.75rem;
        "
        >src/lib/config.ts</code
      >
      to customize the panel name, logo letter, sidebar links, and login page
      copy.
    </p>
  </div>
</template>
